micronaut:
  application:
    name: gallery
  server:
    port: 8081
  security:
    token:
      jwt:
        signatures:
          secret:
            validation:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET} # fix this; wrong
  ssl:
    enabled: true
    port: 8444 # gateway using 8443
    buildSelfSigned: true
  http:
    client:
      ssl:
        enabled: true
        build-self-signed: true
---
datasources:
  default:
    url: ${GALLERY_JDBC_URL}
    username: ${GALLERY_JDBC_USER}
    password: ${GALLERY_JDBC_PASSWORD}
    sql-dialect: 'MYSQL'
---
flyway:
  datasources:
    default:
      enabled: true
