micronaut:
  application:
    name: gallery
  server:
    port: 8081
  netty:
    event-loops:
      other:
        num-threads: 10
        prefer-native-transport: true
    cors:
      enabled: true

  security:
    token:
      jwt:
        signatures:
          secret:
            validation:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET} # fix this; wrong

---
r2dbc:
  datasources:
    default:
      dialect: MYSQL
      url: ${ALLOWANCE_R2DBC_URL}
      username: ${GALLERY_JDBC_USER}
      password: ${GALLERY_JDBC_PASSWORD}
datasources:
  default:
    url: ${GALLERY_JDBC_URL}
    username: ${GALLERY_JDBC_USER}
    password: ${GALLERY_JDBC_PASSWORD}
    sql-dialect: ${GALLERY_JDBC_DIALECT}
#    url: ${BACKUP_GALLERY_JDBC_URL} # for building backup tables
#    username: ${BACKUP_GALLERY_JDBC_USER}
#    password: ${BACKUP_GALLERY_JDBC_PASSWORD}

---
flyway:
  datasources:
    default:
      enabled: true
