micronaut:
  application:
    name: gallery
  server:
    port: 8081
  security:
    token:
      jwt:
        signatures:
          secret:
            validation:
              secret: ${GATEWAY_STAGE_JWT_SIG_GEN}
---
datasources:
  default:
    url: jdbc:mysql://${GALLERY_TESTDB_JAVA_IP}/${GALLERY_TESTDB_JAVA_DBNAME}?serverTimezone=UTC
    username: ${GALLERY_TESTDB_JAVA_USER}
    password: ${GALLERY_TESTDB_JAVA_PASSWORD}
    sql-dialect: 'MYSQL'
---
flyway:
  datasources:
    default:
      locations: classpath:databasemigrations
